[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
EditorStartupMap=/Engine/Maps/Entry

[/Script/Engine.Engine]
; Learning Agents runs training faster with fixed timestep + high max FPS.
bUseFixedFrameRate=False
